kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/sanjitverma/account
steps:
  - name: build
    image: maven:3.3.3-jdk-8-onbuild
    commands:
      - mvn package -DskipTests=false
