insert into ACCOUNT (ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, ACCOUNT_TYPE, BALANCE) values (1, 'PETER', 'PARKER', '1976-03-21', 'DEPOSIT', 5000);
insert into ACCOUNT (ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, ACCOUNT_TYPE, BALANCE) values (2, 'ROSS', 'PARKER', '1980-03-21', 'DEPOSIT',3000);


insert into TRANSACTION (TRANSACTION_TYPE, AMOUNT, DEBIT_ACCOUNT, CREDIT_ACCOUNT, BALANCE_OPERATION, TRANSACTION_DATE) values ('DEBIT', 50, 1,2, 'FUND_TRANSFER', GETDATE());
--insert into TRANSACTION (TRANSACTION_TYPE, AMOUNT, DEBIT_ACCOUNT, CREDIT_ACCOUNT) values ('DEBIT', 50, 1,2);